ifndef::imagesdir[:imagesdir: ../images]

[[section-context-and-scope]]
== Contexto y Alcance


ifdef::arc42help[]
[role="arc42help"]
****
.Contenido  
El ámbito y contexto del sistema, como su nombre lo indica, delimita el sistema (es decir, su ámbito) de todos 
sus interlocutores (sistemas y usuarios vecinos, es decir, el contexto del sistema). De este modo, especifica las interfaces externas.

Si es necesario, diferencie el contexto empresarial (entradas y salidas específicas del dominio) del contexto técnico (canales, protocolos, hardware)..

.Motivación
Las interfaces de dominio y las interfaces técnicas con los socios de comunicación se encuentran entre los aspectos más críticos de su sistema. Asegúrese de comprenderlas por completo.

.Formato
Varias opciones:

* Varios diagramas de contexto
* Listas de socios de comunicación y sus interfaces.


.Más información

Vea https://docs.arc42.org/section-3/[Context and Scope] en la documentación arc42.

****
endif::arc42help[]

=== Contexto de Negocio

image::modelo.svg[Contexto de negocio] 


[options="header",cols="1,2"]
|===
|Elemento|Descripción
| _Usuario_ | _El concursante que interactúa con la aplicación y le puede preguntar al chatbot integrado, y responder a las preguntas mostradas._

| _WIChat_ | _Aplicación web principal donde se desarrolla la lógica del juego._

| _WIChat_ | _Aplicación web principal donde se desarrolla la lógica del juego._

| _Wikidata_ | _Fuente de donde se extraeran las preguntas y las respuestas, las cuales no estarán visibles hasta que el usuario interactue con la aplicación tras responder._
| _LLM_API_ | _API que integra un LLM que se utilizará para generar pistas de forma dinámica y que seguira un diálogo conversacional que ayudará al concursante a responder las preguntas, pero que nunca le dirán implícitamente la respuesta._
| _Base de Datos_ | _Sistema de almacenamiento que guarda información relevante sobre el usuario y anteriores partidas._
|===

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
Especificación de todos los interlocutores (usuarios, sistemas informáticos, etc.) con explicaciones de las entradas y salidas o interfaces específicas del dominio. 
Opcionalmente, puede añadir formatos o protocolos de comunicación específicos del dominio.

.Motivación
Todas las partes interesadas deben comprender qué datos se intercambian con el entorno del sistema.

.Formato
Todo tipo de diagramas que muestran el sistema como una caja negra y especifican las interfaces del dominio con los socios de comunicación.

Como alternativa (o adicionalmente), puede utilizar una tabla. 
El título de la tabla es el nombre de su sistema, las tres columnas contienen el nombre del interlocutor, las entradas y las salidas.

****
endif::arc42help[]

=== Contexto Técnico

ifdef::arc42help[]
[role="arc42help"]
****
.Contenido
Interfaces técnicas (canales y medios de transmisión) que juntan el sistema con su entorno. Además un mapeo del dominio especifico de entrada/salida a los canales, es decir una explicación de qué entrada salida usa cada canal.

.Motivación
Muchos stakeholders toman decisiones arquitectónicas basadas en las interfaces técnicas entre el sistema y su contexto. En especial, los diseñadores de hardware o infraestructura deciden estas interfaces técnicas.

.Forma
E.g. Diagrama UML de despliegue describiendo canales con los sistemas vecinos,
junto a una tabla de mapeo mostrando las relaciones entre canales y la entrada/salida.

****
endif::arc42help[]

==== Diagrama de Despliegue

image::Diagrama-despliegue.svg[Diagrama de Despliegue] 

==== **Explicación de Interfaces Técnicas**

===== **Gateway**
API que hace de enlace entre las distintas partes de la aplicación.

===== **Aplicación React**
React aportará al usuario una interfaz con la que interactuar y responder a las preguntas y por medio de la cual hacer las peticiones
correspondientes a la parte de backEnd de la aplicación.

===== **Base de Datos de Usuarios**
Almacena toda la información referente a los usuarios,datos,historial de partidas.

===== **Servicio de Autenticación**
Interfaz que se comunica con la base de datos de usuarios para comprobar el si el inicio de sesión es válido o no.

===== **Servicio de Usuario**
Interfaz que se comunica con la base de datos de usuarios para consultar y, o actualizar la información referente a las partidas de los mismos.

===== **LLM_Service**
Servicio que procesará las pistas de WikiData y devolverá la respuesta a la pregunta del usuario.
===== **API WikiData**
Wikidata nos aportará todo lo referente a las preguntas, tanto la imágen, como las respuestas y la respuesta correcta, además de que nos permitirá recopilar pistas que servirán al LLM para responder.

==== Mapeo de Canales de Entrada/salida

[options="header",cols="1,2,2"]
|===
| Canal | Entrada | Salida
| Aplicación React | Peticiones HTTP del usuario con las acciones | Respuesta a través de la interfaz.
| Gateway | Peticiones REST de webapp para obtener datos de las preguntas (imágenes,respuestas), o solicitar operaciones como iniciar sesión | Respuesta con la información solicitada en cada caso.
| Servicio Usuario | Datos que se quieren consultar a la base de datos | Respuesta a dicha consulta.
| Servicio Autenticación | Datos de inicio de sesión del usuario | Consulta de comprobación de los datos, para ver si son erróneos o no.
| LLM_Service | Prompt con la solicitud de pistas que quiere el usuario en ese momento | Pista generada por el modelo.
| API Wikidata | Solicitud de las imagenes o pistas en ese momento | Respuesta sobre la imagen solicitada, ya sea en forma de pista, o bien una nueva imagen en caso de que se solicite una nueva pregunta.
| Base de Datos de Usuarios | Instrucciones SQL para consultas o insercioes | Resultado de las consultas o confirmación de las inserciones.
| Prometheus | Métricas de Gateway | métricas en su base de datos.
| Grafana | Métricas organizadas en Prometheus | Visualización de las métricas.
|===
